support RPC for tournament manager API
MahjongRepository/mahjong_soul_api pull request #8
Opened 2022-01-04 17:53 UTC by unStatiK

2022-01-05 01:43 UTC, Nihisil requested changes
Спасибо!

2022-01-05 01:43 UTC, Nihisil commented on README.md
> +1. `protoc --python_out=. protocol.proto`
Это 100% не надо так делать? Строка из какого-то примера была взята

2022-01-05 01:43 UTC, Nihisil commented on example_admin.py
> +access_token = "<token>"
Давай `access_token` получать через входящие параметры, по аналогии с логином и паролем из `example.py`

2022-01-05 01:43 UTC, Nihisil commented on example_admin.py
> +    logging.info("#########################################".format(token))
`.format(token)` тут лишнее? И ниже тоже

2022-01-05 23:27 UTC, unStatiK commented on README.md
> +1. `protoc --python_out=. protocol.proto`
```
$ protoc --python_out=plugins=grpc:. protocol.proto
--python_out: protocol.proto: Unknown generator option: plugins

$ protoc --python_out=grpc:. protocol.proto
--python_out: protocol.proto: Unknown generator option: grpc

$ protoc --python_out=. protocol.proto
$ protoc --version
libprotoc 3.12.3
```

2022-01-06 04:46 UTC, merged

2022-01-06 04:51 UTC, Nihisil commented on README.md
> +1. `protoc --python_out=. protocol.proto`
Странно конечно, ну да ладно

2022-01-06 04:51 UTC, Nihisil commented
Зарелизил эти файлы в новой версии https://pypi.org/project/ms-api/0.10.1.2/